// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ogjmnrdoqmrrtwgcpwkn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9nam1ucmRvcW1ycnR3Z2Nwd2tuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NDk3NTMsImV4cCI6MjA2NjIyNTc1M30.gJhtkQL4M0xEl4K8Wtc_tReSCpcyvMsgeohrf2GPR0U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);